server:
  port: 8082

spring:
  application:
    name: course-service

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:cm_course_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:Post@123}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
      hibernate.physical_naming_strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      hibernate.implicit_naming_strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl

jwt:
  public-key-path: classpath:keys/public_key.pem


app:
  rabbitmq:
    retry:
      max-attempts: 3
      ttl: 5000  # 5 seconds

logging:
  level:
    com.mobisec.in.courseservice: DEBUG
    org.springframework.security: DEBUG
